### PR TITLE
Add jimaku as library

### PR DESCRIPTION
**Pull request by seppo0010**

### CODE REVIEW

**Comment by aeyoll** [comment]
Hello @seppo0010, thanks a lot for your MR.
Can you rebase your branch against `main` and fix the warnings thrown by the pipeline please? Thanks a lot!

**Comment by seppo0010** [comment]
Hi, @aeyoll! I can rebase, but to fix the warning I must rename the `lib` directory because it is significant word in Rust. Are you ok with that? Any suggestion on the alternative name?

**Comment by aeyoll** [comment]
Totaly ok with that, can you rename it `utils`, and rename the `mod.rs`  you added to `lib.rs` please? Thanks a lot!

**Comment by aeyoll** [comment]
Thanks a lot @seppo0010 !

**Pull request merged**
